// Source of findings: the complete Pine pasted by Diego in the 13 Sep thread.
// These are code-audit findings, not a TradingView compiler or strategy result.
export const AUDIT = Object.freeze({
  id:'pine-v151-fidelity-2026-09-13', source:'Pine V15.1 Explainable State Engine, HUD V15.1.1, pasted by owner',
  compiledInTradingView:false, performanceReplayed:false, executionAllowed:false,
  resultSummary:'Première étape terminée : 14 tests logiciels passent, dont 80 000 combinaisons de sizing. Sur l’historique : 519 dernières bougies overnight exclues par l’ancienne horloge ; 1 524 diagnostics de participation M1 changent sur 106 820 minutes comparables avec une moyenne strictement passée. Ces observations ne mesurent pas la rentabilité du scanner.',
  findings:[
    {id:'A01',priority:'P0',title:'Unité de temps opérationnelle',anchor:'is5m = chartSeconds > 60 and chartSeconds <= 300',impact:'Le code autorise aussi les graphiques 2, 3 et 4 minutes, malgré des règles calibrées en M5.',fix:'Exiger exactement 300 secondes pour les plans et alertes ; contexte informatif sur les autres unités.'},
    {id:'A02',priority:'P0',title:'Ancien plan écrasé avant ses sorties',anchor:'Latest-signal Trade Map before Evaluate targets',impact:'Un nouveau plan admis peut remplacer les niveaux avant le contrôle TP/SL de la bougie qui vient de clôturer.',fix:'Évaluer et journaliser les événements de l’ancien plan, puis admettre le nouveau ; séparer census, suivi et carte visible.'},
    {id:'A03',priority:'P0',title:'Sortie complète non terminale',anchor:'planRemainingUnits / if hitTP3',impact:'Une échelle à un contrat peut être entièrement sortie à TP1 tout en restant active jusqu’à TP3, SL ou expiration.',fix:'Clore le suivi dès que les unités restantes atteignent zéro ; conserver le résultat déjà réalisé.'},
    {id:'A04',priority:'P0',title:'Plusieurs événements, une seule alerte conservée',anchor:'f_emitOperationalAlerts / alertText :=',impact:'Les affectations successives effacent les événements précédents, notamment plusieurs TP ou reset et nouveau signal.',fix:'Créer une liste d’événements avec identifiant de plan puis une enveloppe par clôture.'},
    {id:'A05',priority:'P1',title:'Durée graphique et durée du plan couplées',anchor:'maxPlanMinutes = mapBars * ...',impact:'Changer la longueur visuelle modifie l’expiration et les résultats du suivi.',fix:'Séparer horizon analytique fixe et longueur de dessin ; comparer séparément tout changement d’horizon.'},
    {id:'A06',priority:'P1',title:'Budget temporel trop long',anchor:'candidateTimeBudgetATR = math.sqrt(candidateBarsToFlat)',impact:'La faisabilité peut utiliser plus de temps que les 180 minutes d’expiration par défaut.',fix:'Comparer la règle actuelle à min(temps avant flat, horizon du plan) ; ce changement peut modifier les admissions.'},
    {id:'A07',priority:'P1',title:'Fraîcheur S/R partagée entre zones',anchor:'lastResistanceTouchBar / lastSupportTouchBar',impact:'Une touche récente sur une zone peut rendre une autre zone artificiellement fraîche.',fix:'Conserver un identifiant et une dernière touche par cluster stable ; définir fusion et invalidation.'},
    {id:'A08',priority:'P1',title:'Limite de la plage overnight',anchor:'overnightWindow = afterReopen or nyMinuteOfDay < 9 * 60 + 30',impact:'Sur M5, la bougie 09:25–09:30 est exclue lorsque le test utilise l’heure de clôture.',fix:'Définir les fenêtres par ouverture/fermeture explicites ; intégrer la dernière bougie overnight clôturée à 09:30.'},
    {id:'A09',priority:'P1',title:'M1 : une observation intrabougie seulement',anchor:'request.security(syminfo.tickerid, "1", f_microScores())',impact:'Le capteur n’examine pas une séquence complète de cinq minutes et peut varier pendant la M5 courante.',fix:'Distinguer aperçu vivant et capteur figé à la clôture ; tester les tableaux M1 disponibles avec couverture explicite.'},
    {id:'A10',priority:'P1',title:'Pourcentages figés hors configuration calibrée',anchor:'f_tierHist / f_familyHist / next60Z',impact:'Les anciens taux restent affichés après modification des paramètres, du symbole ou de l’unité de temps.',fix:'Attacher une identité source/configuration/période aux statistiques ; afficher non calibré dès divergence.'},
    {id:'A11',priority:'P1',title:'Dédoublonnage temporel sans parent',anchor:'failedBuyWait / fvgBuyWait / boosterBuyWait',impact:'Un cooldown peut supprimer une idée indépendante ou réémettre le même niveau plus tard.',fix:'Exporter tous les membres de famille et des parents causaux ; garder le cooldown actuel comme témoin.'},
    {id:'A12',priority:'P2',title:'FAILED : âge et consommation du pivot',anchor:'buyFailedBreakout / sellFailedBreakout',impact:'Le niveau peut être ancien ou déjà traversé ; la définition actuelle ne distingue pas ces cas.',fix:'Tester séparément fraîcheur, âge ≤8 M5 et profondeur ≤0,5 ATR ; hypothèses, pas corrections validées.'},
    {id:'A13',priority:'P2',title:'FVG : état et invalidation de la zone',anchor:'scannerBullFvgBar / scannerBearFvgBar',impact:'Les zones expirent après 12 barres sans état explicite de consommation ou d’invalidation.',fix:'Tracer création, retest, invalidation et parent ; mesurer avant de changer les signaux.'},
    {id:'A14',priority:'P2',title:'Affichage historique limité',anchor:'historyMode == "Session" ? 60 : 80',impact:'All conserve 80 étiquettes et Session 60 ; les autres marqueurs partagent aussi la limite globale.',fix:'Nommer les limites réelles et séparer journal exhaustif et objets graphiques bornés.'},
    {id:'A15',priority:'P2',title:'Diagnostics figés et courants mélangés',anchor:'planRiskPts / nz(atrRef,1) in HUD',impact:'L’efficacité figée à l’entrée est expliquée avec un ATR courant ; les tooltips T5 parlent encore d’extension H1/H4 retirée.',fix:'Stocker ATR et horloge à l’entrée ; distinguer plan historique et contexte courant ; corriger les textes obsolètes.'},
    {id:'A16',priority:'P2',title:'Calendrier et gaps à formaliser',anchor:'lucidFlatNow / newH4UtcBlock / gapMinutes',impact:'La fermeture est une règle horaire, pas un calendrier férié complet ; un H4 synthétique peut manquer une frontière sans bougie.',fix:'Tester heures d’été, fermetures partielles et plages absentes ; H4 par changement de bucket UTC, avec clôture disponible explicite.'},
    {id:'A17',priority:'P1',title:'Population historique et prix d’entrée',anchor:'e = math.round_to_mintick(close)',impact:'La carte entre à la clôture du signal ; le protocole Time-Pace antérieur décrit une entrée au prochain open. Ces résultats ne sont pas directement interchangeables.',fix:'Comparer identité du scanner, prix d’entrée, horizon, frais, statut ambigu et famille primaire avant de recalibrer.'}
  ]
});
