import {validateRequest,validateForecast} from './bridge.mjs';
const $=id=>document.getElementById(id), fmt=n=>Number(n).toLocaleString('fr-FR',{maximumFractionDigits:2});
const node=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e;};
let registry,request=null,result=null,resources=[],revision=0;
const fileRevisions={request:0,result:0};
async function get(path){const r=await fetch(path,{credentials:'same-origin',cache:'no-store',redirect:'error'});if(!r.ok)throw Error('Chargement indisponible.');return r.json();}
function table(headers,rows){const wrap=node('div','');wrap.className='table-wrap';const t=node('table',''),head=node('thead',''),tr=node('tr','');headers.forEach(x=>{const th=node('th',x);th.scope='col';tr.append(th);});head.append(tr);t.append(head);const body=node('tbody','');rows.forEach(row=>{const tr=node('tr','');row.forEach(v=>tr.append(node('td',String(v))));body.append(tr);});t.append(body);wrap.append(t);return wrap;}
function link(url,label){try{const u=new URL(url);if(u.protocol!=='https:')return node('span',label);const a=node('a',label);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';return a;}catch{return node('span',label);}}
function showResources(){const q=$('resourceSearch').value.trim().toLocaleLowerCase('fr'),type=$('resourceType').value;const selected=resources.filter(r=>(type==='all'||r.type===type)&&`${r.title} ${r.body} ${r.category}`.toLocaleLowerCase('fr').includes(q));$('resourceCount').textContent=`${selected.length} fiche(s) correspondante(s)`;$('resourceList').replaceChildren(...selected.map(r=>{const a=node('article','');a.className='resource';a.append(node('h4',r.title),node('p',r.body));if(r.note){const p=node('p',r.note);p.className='meta';a.append(p);}r.sources.forEach(s=>{const p=node('p','');p.append(link(s.url,s.title));a.append(p);});return a;}));}
async function showForecast(){const own=++revision;$('forecast').hidden=true;$('forecast').replaceChildren();if(!request||!result){$('importStatus').textContent='Charge la sélection et son résultat pour vérifier leur correspondance.';return;}try{await validateForecast(result,request,registry);if(own!==revision)return;$('forecast').append(table(['Début New York','Ouverture prévue','Haut prévu','Bas prévu','Clôture prévue'],result.forecast.map(c=>[new Intl.DateTimeFormat('fr-FR',{timeZone:'America/New_York',dateStyle:'short',timeStyle:'short'}).format(new Date(c.time*1000)),fmt(c.open),fmt(c.high),fmt(c.low),fmt(c.close)])));$('forecast').hidden=false;$('importStatus').textContent=`${request.contract} · sélection et révisions concordantes · calcul ${fmt(result.elapsedSeconds)} s. Prévisions expérimentales, sans ordre.`;}catch(e){if(own===revision)$('importStatus').textContent=e.message;}}
for(const [id,kind] of [['requestFile','request'],['resultFile','result']])$(id).addEventListener('change',async()=>{const own=++fileRevisions[kind];++revision;if(kind==='request')request=null;else result=null;$('forecast').hidden=true;$('importStatus').textContent='Vérification du fichier…';try{const f=$(id).files[0];if(!f||f.size>2_000_000)throw Error('Choisis un fichier JSON de moins de 2 Mo.');const value=JSON.parse(await f.text());if(kind==='request')await validateRequest(value);if(own!==fileRevisions[kind])return;if(kind==='request')request=value;else result=value;await showForecast();}catch(e){if(own===fileRevisions[kind])$('importStatus').textContent=e.message;}});
try{
 const [reg,news,knowledge,sources]=await Promise.all([get('./registry.json'),get('./news-sources.json'),get('./knowledge.json'),get('./knowledge-sources.json')]);registry=reg;
 $('requestFile').disabled=false;$('resultFile').disabled=false;
 $('modelState').textContent=reg.summary;
 const r=reg.diagnostic;if(r?.status==='completed'){$('diagnostic').append(node('p',r.summary),table(['Période','Fenêtres','Erreur Kronos (points)','Dernière clôture constante (points)'],r.periods.map(p=>[p.period,p.count,fmt(p.mae),fmt(p.naiveMae)])),node('p','Erreur absolue moyenne sur les clôtures prévues : plus bas est meilleur. Ce test ne calcule aucun gain de trading.'));}
 const sourceMap=Object.fromEntries(sources.sources.map(s=>[s.source_id,s]));
 resources=[...knowledge.items.map(k=>({type:'knowledge',title:k.title,category:k.category,body:k.explanation,note:k.id==='K04'?'Convention active de Nykuto : RSI=50 si la série est entièrement plate ; la proposition du dossier ne modifie pas ce calcul.':k.limitations,sources:k.source_ids.map(id=>sourceMap[id]).filter(Boolean)})),...news.sources.map(s=>({type:'news',title:s.name,category:s.category,body:s.purpose_fr,note:`Connexion inactive. ${s.caveat_fr||''}`,sources:[{title:s.name,url:s.url}]}))];showResources();
}catch(e){$('modelState').textContent='Le bilan ne peut pas être chargé. Aucune capacité active n’est déduite de cette erreur.';$('resourceCount').textContent=e.message;}
$('resourceSearch').addEventListener('input',showResources);$('resourceType').addEventListener('change',showResources);
